# Spring configuration
spring:
  datasource:
    url: jdbc:mysql://ces-sds2.cjkfoydto4kl.eu-central-1.rds.amazonaws.com:3306/ces?serverTimezone=UTC
    username: XXX
    password: XXX
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update # auto create or update database schema
    database: mysql
  profiles:
    active: dev

# Logger
logging:
  level:
    root: INFO
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO